import parseColor, { type ColorFormats } from "tinycolor2";
import { SHADES_LEVELS } from "./consts";
import { ShadeLevel, ColorPalette, ColorsObject } from "./types";

const colorStringToHsla = (color?: string) => {
    if (!color) {
        return undefined;
    }

    return parseColor(color).toHsl();
};

const hslaToString = (color?: ColorFormats.HSLA) => {
    if (!color) {
        return undefined;
    }

    return `${color.h}, ${color.s * 100}%, ${color.l * 100}%`;
};

const autoGenerateShades = (hsla: ColorFormats.HSLA): Record<ShadeLevel, ColorFormats.HSLA> => {
    const { h, s, l } = hsla;

    return {
        ["100"]: { h, s, l: l + 0.4, a: 1 },
        ["200"]: { h, s, l: l + 0.3, a: 1 },
        ["300"]: { h, s, l: l + 0.2, a: 1 },
        ["400"]: { h, s, l: l + 0.1, a: 1 },
        ["500"]: { h, s, l, a: 1 },
        ["600"]: { h, s, l: l - 0.1, a: 1 },
        ["700"]: { h, s, l: l - 0.2, a: 1 },
        ["800"]: { h, s, l: l - 0.3, a: 1 },
        ["900"]: { h, s, l: l - 0.4, a: 1 }
    };
};

export const assignColorCssVariables = (palette: ColorPalette, colors?: Partial<ColorsObject>) => {
    if (!colors) {
        return;
    }

    const baseColor = colors[palette] || colors[`${palette}500`];
    if (!baseColor) {
        return;
    }
    const defaultColorHslaObject = colorStringToHsla(baseColor);

    const autoGeneratedShades: Partial<Record<ShadeLevel, ColorFormats.HSLA>> =
        defaultColorHslaObject ? autoGenerateShades(defaultColorHslaObject) : {};

    const shadeOverrides: Partial<Record<ShadeLevel, ColorFormats.HSLA>> = SHADES_LEVELS.reduce(
        (acc, level) => {
            const providedShade = colors[`${palette}${level}`];
            if (providedShade) {
                acc[level] = colorStringToHsla(providedShade)!;
            }
            return acc;
        },
        {} as Record<ShadeLevel, ColorFormats.HSLA>
    );

    const mergedShades: Partial<Record<ShadeLevel, ColorFormats.HSLA>> = {
        ...autoGeneratedShades,
        ...shadeOverrides
    };

    const root = document.documentElement;

    for (const shadeLevel in mergedShades) {
        const shade = mergedShades[shadeLevel as ShadeLevel];
        if (shade) {
            const key = `--color-${palette}-${shadeLevel}`;
            const value = hslaToString(shade)!;
            root.style.setProperty(key, value);
        }
    }
};
